### PR TITLE
ci: release-please + luarocks workflow

### PR DESCRIPTION
**Pull request by mrcjkb**
Hey :wave: 

Here's the PR for luarocks support :smile: 

I've copied everything over from markview.nvim.

### CODE REVIEW

**Comment by OXY2DEV** [comment]
Hi @mrcjkb. Sorry for the late reply.

I am currently having an issue with `release-please`. It for some reason makes the exact same changelog every time. And no matter what I do it just increases the main version number.

Do you have a working workflow config since nothing I am trying solves the issue.

**Comment by mrcjkb** [comment]
This has to be a bug with the GitHub action related to the fact that you are targeting the `dev` branch :thinking:

**Comment by OXY2DEV** [comment]
So, do I just set it to the main branch and change the event(since I merge changes from dev so that I don't accidentally break the plugin)?

**Comment by mrcjkb** [comment]
What exactly is your workflow?
If a branch's history gets rewritten (i.e. the commit shas change), that would probably lead to the issues you're observing.

I think setting `main` as the target branch (i.e. removing the `target-branch` input in the workflow file) might be your safest bet.
Also, try deleting the branch created by the release-please action after you close its PR.

**Comment by OXY2DEV** [comment]
> What exactly is your workflow?

[This](https://github.com/OXY2DEV/markview.nvim/blob/main/.github/workflows/release-please.yml)

> If a branch's history gets rewritten (i.e. the commit shas change), that would probably lead to the issues you're observing.

I have only done `git push` & `git pull` so it shouldn't happen. I am also looking at my commit history but don't really see any anomaly(other than commits before adding the workflow not following conventional commits).

> I think setting `main` as the target branch (i.e. removing the `target-branch` input in the workflow file) might be your safest bet. Also, try deleting the branch created by the release-please action after you close its PR.

I have done that. I am going to try one last time. If this doesn't solve the issue then guess I will just have to commit changes to the main branch.

**Comment by mrcjkb** [comment]
> I have only done git push & git pull so it shouldn't happen. I am also looking at my commit history but don't really see any anomaly(other than commits before adding the workflow not following conventional commits).

That shouldn't be a problem. 
I guess it's a bug in release-please then.

**Pull request merged**
